# Generated by Django 4.0.6 on 2024-09-06 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data', models.DateTimeField(verbose_name='Data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField(default=0)),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.balancete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField(default=0)),
                ('foto_boleto', models.ImageField(upload_to='boletos/')),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.balancete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='balancete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario'),
        ),
    ]
