# Generated by Django 4.0.6 on 2024-09-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='foto_boleto',
            field=models.ImageField(blank=True, null=True, upload_to='boletos/'),
        ),
    ]
