# Generated by Django 5.0.8 on 2024-09-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_balancete_usuario_alter_despesa_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.usuario'),
        ),
    ]
