# Generated by Django 5.0.8 on 2024-09-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_balancete_usuario_alter_despesa_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancete',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='usuario',
        ),
    ]
