# Generated by Django 5.0.8 on 2024-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_remove_balancete_usuario_remove_despesa_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='data',
            field=models.DateField(verbose_name='Data de registro'),
        ),
    ]
