# Generated by Django 5.1.3 on 2025-09-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_balancete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='balancete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='financeiro.balancete'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='balancete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='financeiro.balancete'),
        ),
    ]
