name: Django CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.13, 3.12.10]

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mysite/requirements.txt
        pip install pylint

    - name: Verificar código deprecado
      run: |
        pylint mysite/financeiro/ \
          --disable=all \
          --enable=deprecated-module,deprecated-method \
          --fail-under=10
          
    - name: Run Tests
      run: |
        cd mysite
        python manage.py test financeiro

    - name: "Run OWASP Biblioteca"
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "Django Financeiro REPORT"
        path: "./mysite"
        format: "HTML"

    - name: OWASP Report
      uses: actions/upload-artifact@v4
      with:
        name: owasp-report
        path: reports/dependency-check-report.html




   

